### Numpy -> Play with arrays
### Pandas -> dataset
### Matplotlib-> Data Visualisation
### Scipy -> Statistical
### sklearn-> Algorithm

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3,4]

In [3]:
np.array(simple_list)

array([1, 2, 3, 4])

In [4]:
list_of_list=[[2,3,4],[6,7,8],[9,6,5]]

In [5]:
np.array(list_of_list)

array([[2, 3, 4],
       [6, 7, 8],
       [9, 6, 5]])

In [6]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.linspace(0,5,2)

array([0., 5.])

In [25]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [31]:
np.random.rand(3,5)

array([[0.12991426, 0.31755892, 0.72332263, 0.65240077, 0.67420494],
       [0.28994578, 0.21371801, 0.959724  , 0.90870578, 0.81580693],
       [0.88736376, 0.29173264, 0.59665804, 0.88458604, 0.34383211]])

In [34]:
arr=np.random.randn(2,4)

In [35]:
arr

array([[ 0.06681803, -0.84222067,  1.11238614,  0.31595642],
       [-0.48837319,  0.30621115,  0.36366013,  0.30825453]])

In [43]:
np.random.randint(2,5)

4

In [42]:
np.random.randint(20,56,100)

array([21, 55, 27, 45, 42, 42, 42, 47, 51, 40, 47, 40, 29, 38, 47, 49, 37,
       22, 38, 34, 42, 52, 36, 36, 21, 24, 52, 23, 32, 41, 49, 22, 32, 35,
       26, 48, 35, 45, 41, 38, 41, 41, 40, 42, 41, 37, 38, 24, 31, 45, 52,
       28, 51, 41, 32, 53, 49, 42, 28, 39, 47, 27, 49, 23, 52, 29, 53, 42,
       53, 21, 54, 43, 26, 35, 54, 22, 42, 50, 33, 25, 44, 54, 33, 34, 41,
       22, 37, 48, 54, 47, 40, 44, 42, 21, 31, 50, 34, 53, 37, 26])

In [44]:
sample_array=np.arange(30)

In [45]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
sample_array.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [47]:
sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])